export interface User{id:string;email:string;full_name:string;bio?:string;country_of_residence?:string;timezone?:string;avatar_url?:string;push_enabled:boolean;email_digest_enabled:boolean;created_at:string;updated_at:string;}
export interface Membership{member_id:string;role:'admin'|'member';workspace_id:string;display_name:string;workspace_name:string;base_currency:string;}
export interface Workspace{id:string;name:string;description?:string;base_currency:string;family_type?:string;avatar_url?:string;created_at:string;updated_at:string;}
export interface WorkspaceMember{id:string;user_id:string|null;workspace_id:string;display_name:string;role:'admin'|'member';is_proxy:boolean;is_active:boolean;engagement_level?:EngagementLevel;email?:string;avatar_url?:string;created_at:string;updated_at:string;}
export interface WorkspaceSettings{reminder_days_before:number;overdue_notify_after_days:number;weekly_digest_enabled:boolean;reminder_template?:string;invite_message_template?:string;}
export interface Group{id:string;workspace_id:string;name:string;description?:string;created_at:string;member_count?:number;}
export type ContainerType='event'|'recurring';
export type ContainerStatus='active'|'completed'|'archived';
export type EventCategory='celebration'|'memorial'|'financial'|'logistical'|'other';
export type RecurrenceCadence='monthly'|'quarterly'|'yearly'|'custom';
export type LedgerStatus='pending'|'proof_uploaded'|'confirmed'|'disputed'|'resolved';
export type EntryType='contribution'|'correction'|'adjustment';
export type TaskStatus='pending'|'in_progress'|'completed'|'cancelled';
export type DisputeStatus='open'|'resolved';
export type EngagementLevel='active'|'quiet'|'inactive';
export interface Container{id:string;workspace_id:string;name:string;description?:string;type:ContainerType;status:ContainerStatus;category?:EventCategory;event_date?:string;budget_target?:number;base_currency:string;recurrence_cadence?:RecurrenceCadence;cover_photo_url?:string;public_token?:string;progress_pct?:number;total_confirmed?:number;total_expected?:number;participant_count?:number;created_at:string;updated_at:string;}
export interface Participant{id:string;container_id:string;member_id:string;display_name:string;target_amount?:number;base_currency:string;is_active:boolean;created_at:string;}
export interface LedgerEntry{id:string;container_id:string;contributor_id:string;contributor_name:string;amount:number;currency:string;amount_base:number;entry_type:EntryType;status:LedgerStatus;notes?:string;proof_url?:string;proof_filename?:string;confirmed_at?:string;created_at:string;updated_at:string;}
export interface Dispute{id:string;ledger_entry_id:string;workspace_id:string;raised_by_member_id:string;raised_by_name:string;reason:string;status:DisputeStatus;resolution_note?:string;resolved_by_name?:string;resolved_at?:string;created_at:string;notes?:DisputeNote[];}
export interface DisputeNote{id:string;dispute_id:string;member_id:string;member_name:string;note:string;created_at:string;}
export interface Task{id:string;container_id:string;workspace_id:string;title:string;description?:string;status:TaskStatus;assigned_to_member_id?:string;assigned_to_name?:string;due_date?:string;proof_url?:string;created_at:string;updated_at:string;}
export interface Milestone{id:string;workspace_id:string;container_id?:string;title:string;description?:string;milestone_date:string;photo_url?:string;created_at:string;}
export interface Notification{id:string;user_id:string;workspace_id?:string;type:string;title:string;body:string;is_read:boolean;reference_type?:'ledger_entry'|'task'|'dispute'|'container'|'workspace';reference_id?:string;created_at:string;}
export interface Invite{id:string;workspace_id:string;token:string;email?:string;role:'admin'|'member';invited_by_name:string;expires_at:string;accepted_at?:string;created_at:string;}
export interface Cycle{id:string;container_id:string;cycle_number:number;start_date:string;end_date:string;status:'active'|'closed'|'upcoming';total_expected:number;total_collected:number;}
export interface AuditEntry{id:string;action:string;actor_name:string;description:string;created_at:string;}
export interface FileInfo{filename:string;content_type:string;file_size:number;}
export interface ActiveEvent{id:string;name:string;event_date?:string;status:ContainerStatus;progress_pct:number;days_until?:number;total_confirmed?:number;budget_target?:number;}
export interface RecurringPool{id:string;name:string;current_cycle_status?:string;total_expected:number;total_collected:number;}
export interface Deadline{contributor_name:string;container_name:string;container_id:string;due_date:string;days_remaining:number;amount?:number;}
export interface DashboardData{workspace_summary:{member_count:number;admin_count:number;proxy_count:number};active_events:ActiveEvent[];recurring_pools:RecurringPool[];upcoming_deadlines:Deadline[];pending_confirmations:LedgerEntry[];recent_activity:AuditEntry[];unread_notification_count:number;unread_activity_count:number;}
export interface ContainerSummary{container:Container;total_confirmed:number;total_expected:number;total_pending:number;progress_pct:number;participant_count:number;confirmed_count:number;pending_count:number;currency:string;}
