export const KEYS={
  me:()=>['me'] as const,
  workspaces:()=>['workspaces'] as const,
  workspace:(w:string)=>['workspaces',w] as const,
  dashboard:(w:string)=>['workspaces',w,'dashboard'] as const,
  settings:(w:string)=>['workspaces',w,'settings'] as const,

  members: (workspaceId: string) => ['members', workspaceId],
  member: (workspaceId: string, memberId: string) => ['members', workspaceId, memberId],
  engagement: (workspaceId: string) => ['engagement', workspaceId],
  contribution: (workspaceId: string, memberId: string) => ['contribution', workspaceId, memberId],
  profileHistory: (workspaceId: string, memberId: string) => ['profile-history', workspaceId, memberId],

  invites:(w:string)=>['workspaces',w,'invites'] as const,
  invitePreview:(t:string)=>['invites','preview',t] as const,
  overdueSummary:(w:string)=>['workspaces',w,'overdue-summary'] as const,

groups: (w: string) => ['workspaces', w, 'groups'] as const,
group: (w: string, g: string) => ['workspaces', w, 'groups', g] as const,
  containers:(w:string)=>['workspaces',w,'containers'] as const,
  container:(w:string,c:string)=>['workspaces',w,'containers',c] as const,
  summary:(w:string,c:string)=>['workspaces',w,'containers',c,'summary'] as const,
  cycles:(w:string,c:string)=>['workspaces',w,'containers',c,'cycles'] as const,
  participants:(w:string,c:string)=>['workspaces',w,'containers',c,'participants'] as const,
  targetHistory:(w:string,c:string,p:string)=>['workspaces',w,'containers',c,'participants',p,'target-history'] as const,
  cycleTargets:(w:string,c:string,p:string)=>['workspaces',w,'containers',c,'participants',p,'cycle-targets'] as const,
  ledger:(w:string,c:string)=>['workspaces',w,'containers',c,'ledger'] as const,
  disputes:(w:string)=>['workspaces',w,'disputes'] as const,
  dispute:(w:string,d:string)=>['workspaces',w,'disputes',d] as const,
  tasks:(w:string,c:string)=>['workspaces',w,'containers',c,'tasks'] as const,
  timeline:(w:string)=>['workspaces',w,'timeline'] as const,
  notifications:()=>['notifications'] as const,
  notificationCount:()=>['notifications','count'] as const,
  publicContainer:(t:string)=>['public','containers',t] as const,
};
